Add checkbox
js-tasks-ru/htmlcss-20230911-4_ostgerman pull request #18
Opened 2023-10-07 20:38 UTC by yurybabaev

2023-10-07 20:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-07 22:04 UTC, GSemikozov requested changes

2023-10-07 22:04 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  position: absolute;
тогда у родителя надо бы еще position: relative

2023-10-08 14:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-08 14:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-08 16:32 UTC, GSemikozov approved these changes

2023-10-08 16:32 UTC, merged