Feature/lecture4/mobile page
js-tasks-ru/htmlcss-20230911-4_ostgerman pull request #26
Opened 2023-11-01 21:30 UTC by yurybabaev

2023-11-01 21:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-01 21:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-01 21:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-01 21:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-01 21:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-02 07:47 UTC, GSemikozov requested changes

2023-11-02 07:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar_showcase.calendar {
просто .calendar_showcase

2023-11-02 07:47 UTC, GSemikozov commented on components/header/header.css
> +    margin: 38px 0 40px -5px;
отрицательный марджин лишний)

2023-11-02 07:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
кажется лишним (блочный элемент и так тянется на 100% родителя)

2023-11-05 20:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 19:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-09 22:11 UTC, GSemikozov approved these changes

2023-11-09 22:11 UTC, merged