Add histogram
js-tasks-ru/htmlcss-20230911-4_ostgerman pull request #8
Opened 2023-09-25 15:51 UTC by yurybabaev

2023-09-25 15:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-25 22:02 UTC, GSemikozov requested changes

2023-09-25 22:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding: 16px 24px;
`16 24 24`

2023-09-25 22:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 16px;
точно надо? и кажется тогда 39?)

2023-10-03 09:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-03 09:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-03 10:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-03 18:57 UTC, GSemikozov approved these changes

2023-10-03 18:57 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-10-03 19:00 UTC, GSemikozov approved these changes

2023-10-03 19:00 UTC, merged