Add component page layout
js-tasks-ru/htmlcss-20230911-4_ostgerman pull request #9
Opened 2023-10-03 16:54 UTC by yurybabaev

2023-10-03 16:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-03 19:00 UTC, GSemikozov requested changes

2023-10-03 19:00 UTC, GSemikozov commented on components/template/template.css
> +.template__header {
оставляем только `grid-area: header;`, height удаляем, а фон переносим в модификатор самого блока

2023-10-03 19:00 UTC, GSemikozov commented on components/template/template.css
> +  max-width: 1100px;
можем просто завернуть в container

2023-10-03 19:00 UTC, GSemikozov commented on components/template/template.css
> +  grid-area: footer;
оставляем только область, паддинги удаляем, остальное - уносим в сам блок

2023-10-03 19:00 UTC, GSemikozov commented on components/template/template.css
> +.template__footer-text {
оформим как элемент блока футер

2023-10-03 21:51 UTC, yurybabaev commented on components/template/template.css
> +.template__header {
Не очень понимаю. Я верстаю так, чтобы получилось как на макете https://www.figma.com/file/LavZmQfQccqyrTMzoSJYNu/CSS-Course?node-id=17325%3A200&mode=dev Там заголовок - пустая белая полоса. В модификатор какого блока это нужно перенести? У полосы фиксированная высота, почему нужно удалить height?

2023-10-03 21:58 UTC, yurybabaev commented on components/template/template.css
> +  grid-area: footer;
Снова не понимаю. Верстаю по макету: https://www.figma.com/file/LavZmQfQccqyrTMzoSJYNu/CSS-Course?node-id=16769%3A163&mode=dev В какой "сам блок" нужно уносить остальное? Предполагается, что тут нужно использовать универсальный блок header или что-то вроде?

2023-10-03 22:00 UTC, yurybabaev commented on components/template/template.css
> +.template__footer-text {
Тут неявно предполагается, что нужно переиспользовать footer из главной страницы?

2023-10-03 22:02 UTC, yurybabaev commented on components/template/template.css
> +  max-width: 1100px;
Тогда контейнер должен быть с каким-то модификатором, чтобы для него указать `grid-area: main` ? Или можно сделать просто `<main class="template__main container">`?

2023-10-05 20:21 UTC, GSemikozov commented on components/template/template.css
> +.template__header {
на уроке говорил что сразу будем ориентироваться на [главный макет](https://www.figma.com/file/LavZmQfQccqyrTMzoSJYNu/CSS-Course?node-id=16769%3A203&mode=dev)

2023-10-05 20:22 UTC, GSemikozov commented on components/template/template.css
> +.template__header {
внутренние свойства / свойства отвечающие за внутреннюю реализацию блока всегда надо оформлять на уровне этого блока, так что модификатор - для header

2023-10-05 20:24 UTC, GSemikozov commented on components/template/template.css
> +.template__header {
в макете из ссылки выше видно какие элементы будут внутри, + паддинги влияют на высоту, и даже если не будет никакого вложенного контента - хедер все равно будет видимый. Ну и наконец - обычно высота блока зависит от внутреннего содержимого (если поставим 82 а потом накидаем внутрь лого, табы, тайтл - что будет? Вооот)

2023-10-05 20:25 UTC, GSemikozov commented on components/template/template.css
> +  max-width: 1100px;
нет, зачем, просто контейнер использовать внутри template__main

2023-10-05 20:25 UTC, GSemikozov commented on components/template/template.css
> +  grid-area: footer;
см выше. Да, используем блок футер

2023-10-05 20:26 UTC, GSemikozov commented on components/template/template.css
> +.template__footer-text {
очень даже явно)
это ведь элемент блока футер, почему мы его оформляем где-то снаружи, в другом блоке?

2023-10-22 20:56 UTC, GSemikozov approved these changes

2023-10-22 20:56 UTC, merged